FROM node:25.7.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "npm","run","start:dev" ]

EXPOSE 3001

# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
# docker run rabbitmq